export { default as Login } from './Login/Login'
export { default as Map } from './Map/Map'
export { default as Signup } from './Signup/Signup'
export { default as Symptoms } from './Symptoms/Symptoms'
export { default as Terms } from './Terms/Terms'
